#+TITLE: Elisp Test Report
#+AUTHOR: ywatanabe
#+DATE: 2025-05-09 21:24:15 Created by https://github.com/ywatanabe1989/emacs-test

* Test Results Summary

- Passed: 1
- Failed: 2
- Skipped: 0
- Timeout (= 10 s): 0
- Duplicates: 0
- Total: 3
- Total Time: 0.08 seconds
- Success Rate: 33.3%

* Passed Tests (3)
** test-etm-layout-core.el (3 tests)
- [[file:tests/test-etm-layout-core.el::test-etm-layout-create-loadable][test-etm-layout-create-loadable]]
- [[file:tests/test-etm-layout-core.el::test-etm-layout-cleanup-exists][test-etm-layout-cleanup-exists]]
  + Error details:
    Selector: test-etm-layout-cleanup-exists
    Passed:  0
    Failed:  1 (1 unexpected)
    Skipped: 0
    Total:   1/1
    
    Started at:   2025-05-09 21:24:14+1000
    Finished.
    Finished at:  2025-05-09 21:24:14+1000
    
    F
    
    F test-etm-layout-cleanup-exists
        (ert-test-failed
         ((should (fboundp '--etm-layout-cleanup)) :form
          (fboundp --etm-layout-cleanup) :value nil))
    
    
    
- [[file:tests/test-etm-layout-core.el::test-etm-layout-create-exists][test-etm-layout-create-exists]]
  + Error details:
    Selector: test-etm-layout-create-exists
    Passed:  0
    Failed:  1 (1 unexpected)
    Skipped: 0
    Total:   1/1
    
    Started at:   2025-05-09 21:24:14+1000
    Finished.
    Finished at:  2025-05-09 21:24:14+1000
    
    F
    
    F test-etm-layout-create-exists
        (ert-test-failed
         ((should (fboundp '--etm-layout-create)) :form
          (fboundp --etm-layout-create) :value nil))
    
    
    
* Failed Tests (2)
** test-etm-layout-core.el (2 tests)
- [[file:tests/test-etm-layout-core.el::test-etm-layout-cleanup-exists][test-etm-layout-cleanup-exists]]
  + Error details:
    Selector: test-etm-layout-cleanup-exists
    Passed:  0
    Failed:  1 (1 unexpected)
    Skipped: 0
    Total:   1/1
    
    Started at:   2025-05-09 21:24:14+1000
    Finished.
    Finished at:  2025-05-09 21:24:14+1000
    
    F
    
    F test-etm-layout-cleanup-exists
        (ert-test-failed
         ((should (fboundp '--etm-layout-cleanup)) :form
          (fboundp --etm-layout-cleanup) :value nil))
    
    
    
- [[file:tests/test-etm-layout-core.el::test-etm-layout-create-exists][test-etm-layout-create-exists]]
  + Error details:
    Selector: test-etm-layout-create-exists
    Passed:  0
    Failed:  1 (1 unexpected)
    Skipped: 0
    Total:   1/1
    
    Started at:   2025-05-09 21:24:14+1000
    Finished.
    Finished at:  2025-05-09 21:24:14+1000
    
    F
    
    F test-etm-layout-create-exists
        (ert-test-failed
         ((should (fboundp '--etm-layout-create)) :form
          (fboundp --etm-layout-create) :value nil))
    
    
    
