#+TITLE: Elisp Test Report
#+AUTHOR: ywatanabe
#+DATE: 2025-05-09 21:24:17 Created by https://github.com/ywatanabe1989/emacs-test

* Test Results Summary

- Passed: 0
- Failed: 2
- Skipped: 0
- Timeout (= 10 s): 0
- Duplicates: 0
- Total: 2
- Total Time: 0.07 seconds
- Success Rate: 0.0%

* Passed Tests (2)
** test-etm-layout-load.el (2 tests)
- [[file:tests/test-etm-layout-load.el::test-etm-layout-load-loadable][test-etm-layout-load-loadable]]
  + Error details:
    Selector: test-etm-layout-load-loadable
    Passed:  0
    Failed:  1 (1 unexpected)
    Skipped: 0
    Total:   1/1
    
    Started at:   2025-05-09 21:24:17+1000
    Finished.
    Finished at:  2025-05-09 21:24:17+1000
    
    F
    
    F test-etm-layout-load-loadable
        (void-variable etm-layout-save-dir)
    
    
    
- [[file:tests/test-etm-layout-load.el::test-etm-layout-load-function-exists][test-etm-layout-load-function-exists]]
  + Error details:
    Selector: test-etm-layout-load-function-exists
    Passed:  0
    Failed:  1 (1 unexpected)
    Skipped: 0
    Total:   1/1
    
    Started at:   2025-05-09 21:24:17+1000
    Finished.
    Finished at:  2025-05-09 21:24:17+1000
    
    F
    
    F test-etm-layout-load-function-exists
        (ert-test-failed
         ((should (fboundp '--etm-layout-load-all)) :form
          (fboundp --etm-layout-load-all) :value nil))
    
    
    
* Failed Tests (2)
** test-etm-layout-load.el (2 tests)
- [[file:tests/test-etm-layout-load.el::test-etm-layout-load-loadable][test-etm-layout-load-loadable]]
  + Error details:
    Selector: test-etm-layout-load-loadable
    Passed:  0
    Failed:  1 (1 unexpected)
    Skipped: 0
    Total:   1/1
    
    Started at:   2025-05-09 21:24:17+1000
    Finished.
    Finished at:  2025-05-09 21:24:17+1000
    
    F
    
    F test-etm-layout-load-loadable
        (void-variable etm-layout-save-dir)
    
    
    
- [[file:tests/test-etm-layout-load.el::test-etm-layout-load-function-exists][test-etm-layout-load-function-exists]]
  + Error details:
    Selector: test-etm-layout-load-function-exists
    Passed:  0
    Failed:  1 (1 unexpected)
    Skipped: 0
    Total:   1/1
    
    Started at:   2025-05-09 21:24:17+1000
    Finished.
    Finished at:  2025-05-09 21:24:17+1000
    
    F
    
    F test-etm-layout-load-function-exists
        (ert-test-failed
         ((should (fboundp '--etm-layout-load-all)) :form
          (fboundp --etm-layout-load-all) :value nil))
    
    
    
