# Timestamp: "2025-05-09 20:26:46 (ywatanabe)"
# File: /home/ywatanabe/.emacs.d/lisp/emacs-tab-manager/.github/workflows/run_test.yml

name: run_tests
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - 29.2
          - 29.3
          - 29.4
          - snapshot
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: run-tests
        run: |
          git clone https://github.com/ywatanabe1989/elisp-test.git
          ./run_tests.sh -t ./tests --elisp-test ./elisp-test

# EOF