# Timestamp: "2025-05-09 20:26:46 (ywatanabe)"
# File: /home/ywatanabe/.emacs.d/lisp/emacs-tab-manager/.github/workflows/run_test.yml

name: run_tests
on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.emacs_version == 'snapshot' }}
    strategy:
      matrix:
        emacs_version:
          - 27.1
          - 27.2
          - 28.1
          - 28.2
          - 29.1
          - 29.2
          - 29.3
          - 29.4
          - snapshot
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}
      - name: run-tests
        run: |
          # Use native ERT testing instead of elisp-test framework to avoid compatibility issues
          # Run all tests and capture results
          test_results=0
          find tests -name "test-*.el" -type f | while read test_file; do
            echo "Testing: $test_file"
            if ! emacs -Q --batch \
              --eval "(add-to-list 'load-path \".\")" \
              --eval "(add-to-list 'load-path \"./etm-core\")" \
              --eval "(add-to-list 'load-path \"./etm-buffer\")" \
              --eval "(add-to-list 'load-path \"./etm-close\")" \
              --eval "(add-to-list 'load-path \"./etm-keys\")" \
              --eval "(add-to-list 'load-path \"./etm-layout\")" \
              --eval "(add-to-list 'load-path \"./etm-tabs\")" \
              --eval "(add-to-list 'load-path \"$(dirname "$test_file")\")" \
              --eval "(add-to-list 'load-path \"./tests/mocks\")" \
              --eval "(require 'ert)" \
              --eval "(load-file \"$test_file\")" \
              --eval "(ert-run-tests-batch-and-exit)"; then
              echo "FAILED: $test_file"
              test_results=1
            fi
          done
          exit $test_results

# EOF